name: adsunity
description: Ad Network for unity ads
version: 1.0.3
homepage: https://github.com/DevelopGadget/unity-ads

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    platforms:
      android:
        package: com.developgadget.adsunity
        pluginClass: AdsunityPlugin
